//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sca_web_service_reference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://www.sarassist.ca", ConfigurationName="sca_web_service_reference.ICAUpdatesWebserviceSoap")]
    public interface ICAUpdatesWebserviceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetAllOrganizations", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.TaskOfListOfOrganization> GetAllOrganizationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetAllNewsItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.NewsItem[]> GetAllNewsItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetAllPresetCommsPlanItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.CommsPlanItem[]> GetAllPresetCommsPlanItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetAllPresetIncidentObjectives", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.IncidentObjective[]> GetAllPresetIncidentObjectivesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetAllPresetTeamAssignments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.PresetTeamAssignment[]> GetAllPresetTeamAssignmentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetAllPresetSafetyPlans", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.PresetSafetyPlan[]> GetAllPresetSafetyPlansAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetAllDesktopUpdates", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.Update[]> GetAllDesktopUpdatesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/SaveDownloadRecord", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<bool> SaveDownloadRecordAsync(sca_web_service_reference.DownloadRecord record);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetAllCannedComments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.CannedCommsLogEntry[]> GetAllCannedCommentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/RemoveTaskUpdateList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task RemoveTaskUpdateListAsync(System.Guid[] TaskUpdateIDs);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/RemoveTaskUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task RemoveTaskUpdateAsync(System.Guid TaskUpdateID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/SubmitTaskUpdate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<bool> SubmitTaskUpdateAsync(sca_web_service_reference.TaskUpdate update);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/SubmitTaskUpdateAsync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.TaskOfBoolean> SubmitTaskUpdateAsyncAsync(sca_web_service_reference.TaskUpdate update);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetTaskUpdateList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.TaskUpdate[]> GetTaskUpdateListAsync(System.Guid TaskID);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetTaskUpdateListFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.TaskUpdate[]> GetTaskUpdateListFullAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetTaskUpdateDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.TaskUpdate[]> GetTaskUpdateDetailsAsync(System.Guid TaskID, System.Guid machineID, System.DateTime CutoffDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetTaskUpdateDetailsLastByItemIDAsync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.TaskOfListOfTaskUpdate> GetTaskUpdateDetailsLastByItemIDAsyncAsync(System.Guid TaskID, System.Guid machineID, System.DateTime CutoffDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetTaskUpdateDetailByCommand", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.TaskUpdate[]> GetTaskUpdateDetailByCommandAsync(System.Guid TaskID, string CommandName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://www.sarassist.ca/GetAllTaskUpdateDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Task))]
        System.Threading.Tasks.Task<sca_web_service_reference.TaskUpdate[]> GetAllTaskUpdateDetailsAsync(System.DateTime CutoffDate);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class TaskOfListOfOrganization : Task
    {
        
        private Organization[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Organization[] Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class Organization
    {
        
        private System.Guid organizationIDField;
        
        private System.Guid parentOrganizationIDField;
        
        private string organizationNameField;
        
        private string primaryEmailField;
        
        private string primaryPasswordField;
        
        private int userCountField;
        
        private string logoFileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid OrganizationID
        {
            get
            {
                return this.organizationIDField;
            }
            set
            {
                this.organizationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid ParentOrganizationID
        {
            get
            {
                return this.parentOrganizationIDField;
            }
            set
            {
                this.parentOrganizationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrganizationName
        {
            get
            {
                return this.organizationNameField;
            }
            set
            {
                this.organizationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string PrimaryEmail
        {
            get
            {
                return this.primaryEmailField;
            }
            set
            {
                this.primaryEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PrimaryPassword
        {
            get
            {
                return this.primaryPasswordField;
            }
            set
            {
                this.primaryPasswordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int UserCount
        {
            get
            {
                return this.userCountField;
            }
            set
            {
                this.userCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LogoFileName
        {
            get
            {
                return this.logoFileNameField;
            }
            set
            {
                this.logoFileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class CannedCommsLogEntry
    {
        
        private System.Guid cannedIDField;
        
        private string cannedCommentField;
        
        private bool activeField;
        
        private int defaultStatusIDField;
        
        private bool isCriticalField;
        
        private int shortcutField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid CannedID
        {
            get
            {
                return this.cannedIDField;
            }
            set
            {
                this.cannedIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CannedComment
        {
            get
            {
                return this.cannedCommentField;
            }
            set
            {
                this.cannedCommentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int DefaultStatusID
        {
            get
            {
                return this.defaultStatusIDField;
            }
            set
            {
                this.defaultStatusIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool IsCritical
        {
            get
            {
                return this.isCriticalField;
            }
            set
            {
                this.isCriticalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int Shortcut
        {
            get
            {
                return this.shortcutField;
            }
            set
            {
                this.shortcutField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class DownloadRecord
    {
        
        private System.DateTime downloadDateField;
        
        private string downloadIPField;
        
        private string downloadEmailField;
        
        private string downloadVersionField;
        
        private string agencyField;
        
        private string projectNameField;
        
        private string downloadMethodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime DownloadDate
        {
            get
            {
                return this.downloadDateField;
            }
            set
            {
                this.downloadDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DownloadIP
        {
            get
            {
                return this.downloadIPField;
            }
            set
            {
                this.downloadIPField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string DownloadEmail
        {
            get
            {
                return this.downloadEmailField;
            }
            set
            {
                this.downloadEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DownloadVersion
        {
            get
            {
                return this.downloadVersionField;
            }
            set
            {
                this.downloadVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Agency
        {
            get
            {
                return this.agencyField;
            }
            set
            {
                this.agencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ProjectName
        {
            get
            {
                return this.projectNameField;
            }
            set
            {
                this.projectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string DownloadMethod
        {
            get
            {
                return this.downloadMethodField;
            }
            set
            {
                this.downloadMethodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class Update
    {
        
        private System.DateTime updateDateField;
        
        private int updateIDField;
        
        private bool stableReleaseField;
        
        private string descriptionField;
        
        private string projectNameField;
        
        private string downloadURLField;
        
        private string zipDownloadURLField;
        
        private bool visibleField;
        
        private int majorVersionField;
        
        private int minorVersionField;
        
        private int buildNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime UpdateDate
        {
            get
            {
                return this.updateDateField;
            }
            set
            {
                this.updateDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int UpdateID
        {
            get
            {
                return this.updateIDField;
            }
            set
            {
                this.updateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool StableRelease
        {
            get
            {
                return this.stableReleaseField;
            }
            set
            {
                this.stableReleaseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ProjectName
        {
            get
            {
                return this.projectNameField;
            }
            set
            {
                this.projectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DownloadURL
        {
            get
            {
                return this.downloadURLField;
            }
            set
            {
                this.downloadURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ZipDownloadURL
        {
            get
            {
                return this.zipDownloadURLField;
            }
            set
            {
                this.zipDownloadURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool Visible
        {
            get
            {
                return this.visibleField;
            }
            set
            {
                this.visibleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int MajorVersion
        {
            get
            {
                return this.majorVersionField;
            }
            set
            {
                this.majorVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int MinorVersion
        {
            get
            {
                return this.minorVersionField;
            }
            set
            {
                this.minorVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int BuildNumber
        {
            get
            {
                return this.buildNumberField;
            }
            set
            {
                this.buildNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class PresetTeamAssignment
    {
        
        private System.Guid presetIDField;
        
        private string assignmentNameField;
        
        private string selectNameField;
        
        private string descriptionField;
        
        private string specialEquipmentField;
        
        private string assignmentTypeCheckboxesField;
        
        private bool isIRTField;
        
        private bool isTrackingField;
        
        private bool isSoundSweepField;
        
        private bool isDogField;
        
        private bool isType2Field;
        
        private bool isType3Field;
        
        private bool isRRField;
        
        private bool isSWField;
        
        private bool isAviField;
        
        private bool isEvacField;
        
        private bool isMRField;
        
        private bool isBoatField;
        
        private bool isORVField;
        
        private bool isCDFLField;
        
        private bool isUniversalField;
        
        private System.DateTime lastUpdatedUTCField;
        
        private bool activeField;
        
        private System.Guid organizationIDField;
        
        private bool favouriteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid PresetID
        {
            get
            {
                return this.presetIDField;
            }
            set
            {
                this.presetIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AssignmentName
        {
            get
            {
                return this.assignmentNameField;
            }
            set
            {
                this.assignmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string selectName
        {
            get
            {
                return this.selectNameField;
            }
            set
            {
                this.selectNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SpecialEquipment
        {
            get
            {
                return this.specialEquipmentField;
            }
            set
            {
                this.specialEquipmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AssignmentTypeCheckboxes
        {
            get
            {
                return this.assignmentTypeCheckboxesField;
            }
            set
            {
                this.assignmentTypeCheckboxesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool isIRT
        {
            get
            {
                return this.isIRTField;
            }
            set
            {
                this.isIRTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool isTracking
        {
            get
            {
                return this.isTrackingField;
            }
            set
            {
                this.isTrackingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool isSoundSweep
        {
            get
            {
                return this.isSoundSweepField;
            }
            set
            {
                this.isSoundSweepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool isDog
        {
            get
            {
                return this.isDogField;
            }
            set
            {
                this.isDogField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool isType2
        {
            get
            {
                return this.isType2Field;
            }
            set
            {
                this.isType2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool isType3
        {
            get
            {
                return this.isType3Field;
            }
            set
            {
                this.isType3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool isRR
        {
            get
            {
                return this.isRRField;
            }
            set
            {
                this.isRRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool isSW
        {
            get
            {
                return this.isSWField;
            }
            set
            {
                this.isSWField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool isAvi
        {
            get
            {
                return this.isAviField;
            }
            set
            {
                this.isAviField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool isEvac
        {
            get
            {
                return this.isEvacField;
            }
            set
            {
                this.isEvacField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool isMR
        {
            get
            {
                return this.isMRField;
            }
            set
            {
                this.isMRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool isBoat
        {
            get
            {
                return this.isBoatField;
            }
            set
            {
                this.isBoatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool isORV
        {
            get
            {
                return this.isORVField;
            }
            set
            {
                this.isORVField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool isCDFL
        {
            get
            {
                return this.isCDFLField;
            }
            set
            {
                this.isCDFLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public bool isUniversal
        {
            get
            {
                return this.isUniversalField;
            }
            set
            {
                this.isUniversalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public System.DateTime LastUpdatedUTC
        {
            get
            {
                return this.lastUpdatedUTCField;
            }
            set
            {
                this.lastUpdatedUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public System.Guid OrganizationID
        {
            get
            {
                return this.organizationIDField;
            }
            set
            {
                this.organizationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public bool Favourite
        {
            get
            {
                return this.favouriteField;
            }
            set
            {
                this.favouriteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class NewsItem
    {
        
        private System.Guid idField;
        
        private System.DateTime newsDateField;
        
        private System.DateTime lastUpdatedUTCField;
        
        private string newsTitleField;
        
        private string newsTextField;
        
        private string newsUrlField;
        
        private bool readLocallyField;
        
        private bool activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime NewsDate
        {
            get
            {
                return this.newsDateField;
            }
            set
            {
                this.newsDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime LastUpdatedUTC
        {
            get
            {
                return this.lastUpdatedUTCField;
            }
            set
            {
                this.lastUpdatedUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string NewsTitle
        {
            get
            {
                return this.newsTitleField;
            }
            set
            {
                this.newsTitleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string NewsText
        {
            get
            {
                return this.newsTextField;
            }
            set
            {
                this.newsTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NewsUrl
        {
            get
            {
                return this.newsUrlField;
            }
            set
            {
                this.newsUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool ReadLocally
        {
            get
            {
                return this.readLocallyField;
            }
            set
            {
                this.readLocallyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PresetSafetyPlan))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(IncidentObjective))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CommsPlanItem))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public abstract partial class SyncableItem
    {
        
        private System.Guid idField;
        
        private bool activeField;
        
        private int opPeriodField;
        
        private System.DateTime lastUpdatedUTCField;
        
        private System.Guid caltopoUUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool Active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int OpPeriod
        {
            get
            {
                return this.opPeriodField;
            }
            set
            {
                this.opPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime LastUpdatedUTC
        {
            get
            {
                return this.lastUpdatedUTCField;
            }
            set
            {
                this.lastUpdatedUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.Guid CaltopoUUID
        {
            get
            {
                return this.caltopoUUIDField;
            }
            set
            {
                this.caltopoUUIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class PresetSafetyPlan : SyncableItem
    {
        
        private System.Guid safetyPlanTemplateIDField;
        
        private string hazardNameField;
        
        private string descriptionField;
        
        private string precautionsField;
        
        private string specialInstructionsField;
        
        private string[] additionalPPEField;
        
        private string[] checkedFieldNamesField;
        
        private bool isUniversalField;
        
        private System.Guid organizationIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid SafetyPlanTemplateID
        {
            get
            {
                return this.safetyPlanTemplateIDField;
            }
            set
            {
                this.safetyPlanTemplateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HazardName
        {
            get
            {
                return this.hazardNameField;
            }
            set
            {
                this.hazardNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Precautions
        {
            get
            {
                return this.precautionsField;
            }
            set
            {
                this.precautionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SpecialInstructions
        {
            get
            {
                return this.specialInstructionsField;
            }
            set
            {
                this.specialInstructionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=5)]
        public string[] additionalPPE
        {
            get
            {
                return this.additionalPPEField;
            }
            set
            {
                this.additionalPPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        public string[] checkedFieldNames
        {
            get
            {
                return this.checkedFieldNamesField;
            }
            set
            {
                this.checkedFieldNamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool isUniversal
        {
            get
            {
                return this.isUniversalField;
            }
            set
            {
                this.isUniversalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.Guid OrganizationID
        {
            get
            {
                return this.organizationIDField;
            }
            set
            {
                this.organizationIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class IncidentObjective : SyncableItem
    {
        
        private System.Guid presetObjectiveIDField;
        
        private string objectiveField;
        
        private int priorityField;
        
        private bool isUniversalField;
        
        private System.DateTime presetLastUpdatedUTCField;
        
        private System.Guid taskIDField;
        
        private System.Guid incidentObjectiveIDField;
        
        private System.DateTime objectiveLastUpdatedUTCField;
        
        private System.Guid organizationIDField;
        
        private bool completedField;
        
        private string copyNextOpTextField;
        
        private System.Guid parentObjectiveIDField;
        
        private string[] templateStrategiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid PresetObjectiveID
        {
            get
            {
                return this.presetObjectiveIDField;
            }
            set
            {
                this.presetObjectiveIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Objective
        {
            get
            {
                return this.objectiveField;
            }
            set
            {
                this.objectiveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Priority
        {
            get
            {
                return this.priorityField;
            }
            set
            {
                this.priorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isUniversal
        {
            get
            {
                return this.isUniversalField;
            }
            set
            {
                this.isUniversalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime PresetLastUpdatedUTC
        {
            get
            {
                return this.presetLastUpdatedUTCField;
            }
            set
            {
                this.presetLastUpdatedUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.Guid TaskID
        {
            get
            {
                return this.taskIDField;
            }
            set
            {
                this.taskIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public System.Guid IncidentObjectiveID
        {
            get
            {
                return this.incidentObjectiveIDField;
            }
            set
            {
                this.incidentObjectiveIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime ObjectiveLastUpdatedUTC
        {
            get
            {
                return this.objectiveLastUpdatedUTCField;
            }
            set
            {
                this.objectiveLastUpdatedUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.Guid OrganizationID
        {
            get
            {
                return this.organizationIDField;
            }
            set
            {
                this.organizationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool Completed
        {
            get
            {
                return this.completedField;
            }
            set
            {
                this.completedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CopyNextOpText
        {
            get
            {
                return this.copyNextOpTextField;
            }
            set
            {
                this.copyNextOpTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.Guid ParentObjectiveID
        {
            get
            {
                return this.parentObjectiveIDField;
            }
            set
            {
                this.parentObjectiveIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=12)]
        public string[] TemplateStrategies
        {
            get
            {
                return this.templateStrategiesField;
            }
            set
            {
                this.templateStrategiesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class CommsPlanItem : SyncableItem
    {
        
        private System.Guid itemIDField;
        
        private string commsSystemField;
        
        private string callSignField;
        
        private string commsFunctionField;
        
        private string channelIDField;
        
        private string channelNumberField;
        
        private string frequencyField;
        
        private string rxFrequencyField;
        
        private string txFrequencyField;
        
        private string commentsField;
        
        private bool isRepeaterField;
        
        private bool isUniversalField;
        
        private System.Guid organizationIDField;
        
        private int opsPeriodField;
        
        private string rxToneField;
        
        private string txToneField;
        
        private string assignmentField;
        
        private bool usedForAircraftField;
        
        private System.Guid templateItemIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ItemID
        {
            get
            {
                return this.itemIDField;
            }
            set
            {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CommsSystem
        {
            get
            {
                return this.commsSystemField;
            }
            set
            {
                this.commsSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CallSign
        {
            get
            {
                return this.callSignField;
            }
            set
            {
                this.callSignField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string CommsFunction
        {
            get
            {
                return this.commsFunctionField;
            }
            set
            {
                this.commsFunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ChannelID
        {
            get
            {
                return this.channelIDField;
            }
            set
            {
                this.channelIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ChannelNumber
        {
            get
            {
                return this.channelNumberField;
            }
            set
            {
                this.channelNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Frequency
        {
            get
            {
                return this.frequencyField;
            }
            set
            {
                this.frequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RxFrequency
        {
            get
            {
                return this.rxFrequencyField;
            }
            set
            {
                this.rxFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string TxFrequency
        {
            get
            {
                return this.txFrequencyField;
            }
            set
            {
                this.txFrequencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool IsRepeater
        {
            get
            {
                return this.isRepeaterField;
            }
            set
            {
                this.isRepeaterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool isUniversal
        {
            get
            {
                return this.isUniversalField;
            }
            set
            {
                this.isUniversalField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.Guid OrganizationID
        {
            get
            {
                return this.organizationIDField;
            }
            set
            {
                this.organizationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int OpsPeriod
        {
            get
            {
                return this.opsPeriodField;
            }
            set
            {
                this.opsPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string RxTone
        {
            get
            {
                return this.rxToneField;
            }
            set
            {
                this.rxToneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string TxTone
        {
            get
            {
                return this.txToneField;
            }
            set
            {
                this.txToneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Assignment
        {
            get
            {
                return this.assignmentField;
            }
            set
            {
                this.assignmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool UsedForAircraft
        {
            get
            {
                return this.usedForAircraftField;
            }
            set
            {
                this.usedForAircraftField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public System.Guid TemplateItemID
        {
            get
            {
                return this.templateItemIDField;
            }
            set
            {
                this.templateItemIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class TaskUpdate
    {
        
        private System.Guid updateIDField;
        
        private System.Guid taskIDField;
        
        private System.DateTime lastUpdatedUTCField;
        
        private int softwareVersionMajorField;
        
        private int softwareVersionMinorField;
        
        private int softwareVersionBuildField;
        
        private string commandNameField;
        
        private string objectTypeField;
        
        private string sourceField;
        
        private string createdByRoleNameField;
        
        private System.Guid itemIDField;
        
        private SyncableItem dataField;
        
        private string dataAsJSONField;
        
        private bool processedLocallyField;
        
        private bool uploadedSuccessfullyField;
        
        private System.Guid machineIDField;
        
        private string dataEncField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid UpdateID
        {
            get
            {
                return this.updateIDField;
            }
            set
            {
                this.updateIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid TaskID
        {
            get
            {
                return this.taskIDField;
            }
            set
            {
                this.taskIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime LastUpdatedUTC
        {
            get
            {
                return this.lastUpdatedUTCField;
            }
            set
            {
                this.lastUpdatedUTCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SoftwareVersionMajor
        {
            get
            {
                return this.softwareVersionMajorField;
            }
            set
            {
                this.softwareVersionMajorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SoftwareVersionMinor
        {
            get
            {
                return this.softwareVersionMinorField;
            }
            set
            {
                this.softwareVersionMinorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int SoftwareVersionBuild
        {
            get
            {
                return this.softwareVersionBuildField;
            }
            set
            {
                this.softwareVersionBuildField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CommandName
        {
            get
            {
                return this.commandNameField;
            }
            set
            {
                this.commandNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ObjectType
        {
            get
            {
                return this.objectTypeField;
            }
            set
            {
                this.objectTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Source
        {
            get
            {
                return this.sourceField;
            }
            set
            {
                this.sourceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CreatedByRoleName
        {
            get
            {
                return this.createdByRoleNameField;
            }
            set
            {
                this.createdByRoleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.Guid ItemID
        {
            get
            {
                return this.itemIDField;
            }
            set
            {
                this.itemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public SyncableItem Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DataAsJSON
        {
            get
            {
                return this.dataAsJSONField;
            }
            set
            {
                this.dataAsJSONField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool ProcessedLocally
        {
            get
            {
                return this.processedLocallyField;
            }
            set
            {
                this.processedLocallyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool UploadedSuccessfully
        {
            get
            {
                return this.uploadedSuccessfullyField;
            }
            set
            {
                this.uploadedSuccessfullyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public System.Guid MachineID
        {
            get
            {
                return this.machineIDField;
            }
            set
            {
                this.machineIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DataEnc
        {
            get
            {
                return this.dataEncField;
            }
            set
            {
                this.dataEncField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaskOfListOfTaskUpdate))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaskOfBoolean))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TaskOfListOfOrganization))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class Task
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class TaskOfListOfTaskUpdate : Task
    {
        
        private TaskUpdate[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public TaskUpdate[] Result
        {
            get
            {
                return this.resultField;
            }
            set
            {
                this.resultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://www.sarassist.ca")]
    public partial class TaskOfBoolean : Task
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ICAUpdatesWebserviceSoapChannel : sca_web_service_reference.ICAUpdatesWebserviceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CAUpdatesWebserviceSoapClient : System.ServiceModel.ClientBase<sca_web_service_reference.ICAUpdatesWebserviceSoap>, sca_web_service_reference.ICAUpdatesWebserviceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CAUpdatesWebserviceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CAUpdatesWebserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), CAUpdatesWebserviceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CAUpdatesWebserviceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CAUpdatesWebserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CAUpdatesWebserviceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CAUpdatesWebserviceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CAUpdatesWebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.TaskOfListOfOrganization> GetAllOrganizationsAsync()
        {
            return base.Channel.GetAllOrganizationsAsync();
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.NewsItem[]> GetAllNewsItemsAsync()
        {
            return base.Channel.GetAllNewsItemsAsync();
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.CommsPlanItem[]> GetAllPresetCommsPlanItemsAsync()
        {
            return base.Channel.GetAllPresetCommsPlanItemsAsync();
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.IncidentObjective[]> GetAllPresetIncidentObjectivesAsync()
        {
            return base.Channel.GetAllPresetIncidentObjectivesAsync();
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.PresetTeamAssignment[]> GetAllPresetTeamAssignmentsAsync()
        {
            return base.Channel.GetAllPresetTeamAssignmentsAsync();
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.PresetSafetyPlan[]> GetAllPresetSafetyPlansAsync()
        {
            return base.Channel.GetAllPresetSafetyPlansAsync();
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.Update[]> GetAllDesktopUpdatesAsync()
        {
            return base.Channel.GetAllDesktopUpdatesAsync();
        }
        
        public System.Threading.Tasks.Task<bool> SaveDownloadRecordAsync(sca_web_service_reference.DownloadRecord record)
        {
            return base.Channel.SaveDownloadRecordAsync(record);
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.CannedCommsLogEntry[]> GetAllCannedCommentsAsync()
        {
            return base.Channel.GetAllCannedCommentsAsync();
        }
        
        public System.Threading.Tasks.Task RemoveTaskUpdateListAsync(System.Guid[] TaskUpdateIDs)
        {
            return base.Channel.RemoveTaskUpdateListAsync(TaskUpdateIDs);
        }
        
        public System.Threading.Tasks.Task RemoveTaskUpdateAsync(System.Guid TaskUpdateID)
        {
            return base.Channel.RemoveTaskUpdateAsync(TaskUpdateID);
        }
        
        public System.Threading.Tasks.Task<bool> SubmitTaskUpdateAsync(sca_web_service_reference.TaskUpdate update)
        {
            return base.Channel.SubmitTaskUpdateAsync(update);
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.TaskOfBoolean> SubmitTaskUpdateAsyncAsync(sca_web_service_reference.TaskUpdate update)
        {
            return base.Channel.SubmitTaskUpdateAsyncAsync(update);
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.TaskUpdate[]> GetTaskUpdateListAsync(System.Guid TaskID)
        {
            return base.Channel.GetTaskUpdateListAsync(TaskID);
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.TaskUpdate[]> GetTaskUpdateListFullAsync()
        {
            return base.Channel.GetTaskUpdateListFullAsync();
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.TaskUpdate[]> GetTaskUpdateDetailsAsync(System.Guid TaskID, System.Guid machineID, System.DateTime CutoffDate)
        {
            return base.Channel.GetTaskUpdateDetailsAsync(TaskID, machineID, CutoffDate);
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.TaskOfListOfTaskUpdate> GetTaskUpdateDetailsLastByItemIDAsyncAsync(System.Guid TaskID, System.Guid machineID, System.DateTime CutoffDate)
        {
            return base.Channel.GetTaskUpdateDetailsLastByItemIDAsyncAsync(TaskID, machineID, CutoffDate);
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.TaskUpdate[]> GetTaskUpdateDetailByCommandAsync(System.Guid TaskID, string CommandName)
        {
            return base.Channel.GetTaskUpdateDetailByCommandAsync(TaskID, CommandName);
        }
        
        public System.Threading.Tasks.Task<sca_web_service_reference.TaskUpdate[]> GetAllTaskUpdateDetailsAsync(System.DateTime CutoffDate)
        {
            return base.Channel.GetAllTaskUpdateDetailsAsync(CutoffDate);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ICAUpdatesWebserviceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ICAUpdatesWebserviceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ICAUpdatesWebserviceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://sarassist.ca/ICAUpdatesWebservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ICAUpdatesWebserviceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://sarassist.ca/ICAUpdatesWebservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ICAUpdatesWebserviceSoap,
            
            ICAUpdatesWebserviceSoap12,
        }
    }
}
